name: Test API

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
        
    steps:
    - uses: actions/checkout@master
    
    - name: Set Up .NetCore
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.408'
        
    - name: Dotnet Restore
      run: dotnet restore
        
    - name: Build with dotnet
      run: dotnet publish -o .\publish    
        
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.5
      
    - name: Install Opentest 
      run: |
        npm install opentest -g
    - name: Move Selenium
      run: .\.github\scripts\drive.ps1 ${{github.workspace}}
    
    - name: Start Script
      run: .\.github\scripts\startApi.ps1 ${{github.workspace}}

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v2
      with:
        report_paths: '**\test-results\*.xml'
